kind: pipeline
type: docker
name: docker-image-pipeline

steps:
  # Step to build and push Docker image
  - name: docker build & push
    image: plugins/docker
    settings:
      repo: sanmarg11/drone-helloworld
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # Step to run Trivy vulnerability scan
  - name: trivy scan
    image: aquasec/trivy:latest
    commands:
      - trivy image --exit-code 0 --severity HIGH,CRITICAL sanmarg11/drone-helloworld:${DRONE_COMMIT_SHA}

