kind: pipeline
type: docker
name: docker-image-pipeline

environment:
  DOCKER_USERNAME: sanmarg11
  REPO_NAME: drone-helloworld
  DOCKER_HOST: tcp://localhost:2375  # Ensure the pipeline connects to the correct Docker daemon

steps:
  - name: docker build
    image: plugins/docker  # Use the official Docker plugin
    settings:
      repo: $DOCKER_USERNAME/$REPO_NAME
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      build_args: # optional, if you need to pass build arguments
        ARG_NAME: value
    environment:
      DOCKER_HOST: tcp://0.0.0.0:2375  # Set the correct Docker Daemon endpoint
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: trivy scan
    image: aquasec/trivy:latest
    environment:
      TRIVY_NON_SSL: "true"
    commands:
      - trivy image --exit-code 0 --severity HIGH,CRITICAL $DOCKER_USERNAME/$REPO_NAME:$DRONE_COMMIT_SHA

  - name: docker push
    image: plugins/docker
    settings:
      repo: $DOCKER_USERNAME/$REPO_NAME
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
