kind: pipeline
type: docker
name: docker-image-pipeline

environment:
  DOCKER_USERNAME: sanmarg11
  REPO_NAME: drone-helloworld
  DOCKER_HOST: tcp://localhost:2375  # Docker daemon endpoint

steps:
  # Step for building the Docker image
  - name: docker build
    image: docker:20-dind  # Use Docker-in-Docker 20.x
    privileged: true  # Required for Docker-in-Docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock  # Bind Docker socket
    environment:
      DOCKER_HOST: tcp://localhost:2375  # Set the Docker Daemon endpoint
    commands:
      - docker build -t $DOCKER_USERNAME/$REPO_NAME:$DRONE_COMMIT_SHA .
      - docker tag $DOCKER_USERNAME/$REPO_NAME:$DRONE_COMMIT_SHA $DOCKER_USERNAME/$REPO_NAME:latest

  # Step for running Trivy security scan
  - name: trivy scan
    image: aquasec/trivy:latest
    environment:
      TRIVY_NON_SSL: "true"
    commands:
      - trivy image --exit-code 0 --severity HIGH,CRITICAL $DOCKER_USERNAME/$REPO_NAME:$DRONE_COMMIT_SHA

  # Step for pushing the Docker image to Docker Hub
  - name: docker push
    image: plugins/docker
    settings:
      repo: $DOCKER_USERNAME/$REPO_NAME
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock  # Use Docker socket for communication
